language: ruby
rvm:
- 2.3.1
before_install:
- curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.0.3
- gem install bundler -v 1.11.2
install:
- chef exec bundle install --jobs=3 --retry=3
before_script: chef exec rake setup_test_environment
script: "./.travis_install.sh"
notifications:
  slack:
    secure: C52GDOF0/0PbOkFrBvX9+aBtcxKNnKLYQdJ4/VUDv/vtyp8FIUXn3C4JxFSMfGm3Uhu/DkkXDsoouv6tfn0iXfoVkCUpykaNQUBcnPZDBAQesshJn7ClKzAqY+EgRkUgeL3amil3iAdiBtzTg/cUbWfm0Pi0HsdadQ2OfWgjcu0=
